services:
  mysql:
    container_name: spring_web
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: "spring_web"
      MYSQL_ROOT_PASSWORD: "1234"
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/volume:/var/lib/grafana
  redis:
    image: 'redis:6.0.20'
    container_name: redis_security
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data
#  zookeeper:
#    image: 'bitnami/zookeeper:3.7.2'
#    container_name: coupon_zookeeper
#    ports:
#      - 2181:2181
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    volumes:
#      - ./.data/zookeeper/data:/bitnami/zookeeper/data
#      - ./.data/zookeeper/datalog:/bitnami/zookeeper/datalog
#      - ./.data/zookeeper/logs:/bitnami/zookeeper/logs
#
#  kafka:
#    image: 'bitnami/kafka:3.6.0'
#    container_name: coupon_kafka
#    hostname: coupon_kafka
#    ports:
#      - 19092
#      - "9092:9092"
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
#      - KAFKA_CFG_LISTENERS=CLIENT://:19092,EXTERNAL://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:19092,EXTERNAL://localhost:9092
#      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
#    depends_on:
#      - zookeeper
#    volumes:
#      - ./.data/kafka1:/bitnami/kafka/data
#  kafka-ui:
#    image: 'provectuslabs/kafka-ui:v0.7.1'
#    container_name: kafka-coupon_ui
#    ports:
#      - "8089:8080"
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:19092
#    depends_on:
#      - zookeeper
#      - kafka
