# default
spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_web
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        session_factory:
          statement_inspector: com.web.global.config.sql.QueryCountInspector
  data:
    redis:
      host: localhost
      port: 6379
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
management:
  server:
    port: 8080
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*" #엔드포인트 기능을 액추에이터에 노출시키겠다는것
server:
  tomcat:
    mbeanregistry:
      enabled: true #tomcat 메트릭
logging:
  level:
    root: INFO
jwt:
  expire_time: 86400000 #1day
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

#---
#spring:
#  config:
#    activate:
#      on-profile: test
#  jpa:
#    database: h2
#jwt:
#  expire_time: 86400000 #1day
#  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
#payment:
#  imp:
#    key: fake-key-for-test
#    secret: fake-secret-for-test